name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run build
      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # must be the PRIVATE key; no passphrase

      - name: Add remote host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via scp
        run: |
          scp -o StrictHostKeyChecking=yes -r dist/* root@${{ secrets.SSH_HOST }}:~/var/www/
          # if non-standard port: add -P <port>
      - name: Restart Web Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{ secrets.SSH_HOST }} "cd /var/www/ && npm install && pm2 restart all"
