name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v4

      - run: npm ci
      - run: npm run build

      - name: Install OpenSSH client
        run: |
          apt-get update
          apt-get install -y --no-install-recommends openssh-client

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT || 22 }}" -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy via scp
        run: scp -P "${{ secrets.SSH_PORT || 22 }}" -i ~/.ssh/id_rsa -r dist/* "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/"

      - name: Restart Web Server
        run: ssh -p "${{ secrets.SSH_PORT || 22 }}" -i ~/.ssh/id_rsa "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" 'cd /var/www && npm ci --omit=dev && pm2 restart all'
