name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v4

      - run: npm ci
      - run: npm run build

      - name: Install OpenSSH client
        run: |
          apt-get update
          apt-get install -y --no-install-recommends openssh-client

      - name: Write SSH key (strip CRLF) and known_hosts
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          tr -d '\r' < ~/.ssh/id_rsa > ~/.ssh/id_rsa.clean && mv ~/.ssh/id_rsa.clean ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy via scp
        run: scp -i ~/.ssh/id_rsa -r dist/* "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/"

      - name: Restart Web Server
        run: ssh -i ~/.ssh/id_rsa "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" 'cd /var/www && npm ci --omit=dev && pm2 restart all'
