name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run build
      - name: Get SSH Key and set permissions
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      - name: Deploy to Server
        run: |
          sudo scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./dist/* root@${{ secrets.SSH_HOST }}:~/var/www/
      - name: Restart Web Server
        run: |
          sudo ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{ secrets.SSH_HOST }} "cd ~/var/www/ && npm install && pm2 restart all"
